# Generated by Django 5.2.5 on 2025-08-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_UniqueNumberRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BigIntegerField()),
                ('end', models.BigIntegerField()),
                ('current', models.BigIntegerField(default=0)),
                ('server_id', models.CharField(default='server1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_URL_Shortner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('long_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
